apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: tooling
    tier: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: tooling
    tier: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: tooling
    tier: mysql
spec:
  selector:
    matchLabels:
      app: tooling
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tooling
        tier: mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: toolingdb
            - name: MYSQL_USER
              value: john
            - name: MYSQL_PASSWORD
              value: pass
          ports:
            - containerPort: 3306
              name: mysql
